version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations && 
             python manage.py migrate &&
             exec gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URL=postgres://sg_account:${POSTGRES_PASSWORD}@db:5432/notesdb
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=sg_account
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  static_volume:
